### PR TITLE
Fix: Variable interpolation

### LINKED ISSUE #166: Most query types are not working with dashboard variabels
After importing the [default dashboard for GitHub](https://grafana.com/grafana/dashboards/14000), out of the box it returns error on most the panels as show below. The message `Could not resolve to a Repository with the name '$organization/$repository'.` appears for commits, contributors, milestones, packages.. it works for releases and tags.

Adding the owner and repository manually in the panel query edit screen works fine. It seems that the variables are not working correctly with the panels query for certain query types.

Screen Shot 2022-05-02 at 5 45 23 PM

Environment: Docker Community Edition, v8.5.1 (61fe4a1859)

### PR DESCRIPTION
**Pull request by zoltanbedi**
Fixes #166
Fixes https://github.com/grafana/support-escalations/issues/2519

### CODE REVIEW

**Review by dprokop — APPROVED** [review]

File: src/variables.ts [hunk 1]
```diff
@@ -15,7 +15,7 @@ export const replaceVariables = (t: TemplateSrv, query: GitHubQuery, scoped: Sco
   let updatedQuery = { ...query };
```
Comment (scottlepp) [inline src/variables.ts:15]: seems like this isn't necessary.  just doing a shallow copy
